[env]
RUSTFLAGS="-D warnings"
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.clippy]
install_crate = { rustup_component_name = "clippy" }
command = "cargo"
args=["clippy","--","-D","clippy::all","-D","warnings"]

[tasks.fmtcheck]
install_crate = "rustfmt"
command = "cargo"
args=["fmt", "--", "--check"]

[tasks.lint]
dependencies=[
	"clippy",
	"fmtcheck",
]
[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["lint"]

[tasks.pre-push]
dependencies = [
    "lint",
    "test",
]
