#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -eu

cr=$(dirname $0)
cd $cr
remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		# Handle delete
		:
	else
		if [ "$remote_sha" = $z40 ]
		then
			range="$local_sha"
		else
			range="$remote_sha..$local_sha"
		fi
	fi
	./hooks/pre-push/runner.sh $1 $2 $local_ref $local_sha $remote_ref $remote_sha $range
done

exit 0



