#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -eu

cr=$(dirname $0)
cd $cr
remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		# Handle delete
		:
	else
		if [ "$remote_sha" = $z40 ]
		then
			# New branch, examine all commits
			range="$local_sha"
		else
			# Update to existing branch, examine new commits
			range="$remote_sha..$local_sha"
		fi

		# Check for WIP commit
		commit=`git rev-list -n 1 --grep '^WIP' "$range"`
		if [ -n "$commit" ]
		then
			echo >&2 "Found WIP commit in $local_ref, not pushing"
			exit 1
		fi
	fi
	echo "local_ref:$local_ref,remote:$remote,url:$url"
	./hooks/pre-push/cargo_lint.sh &
	./hooks/pre-push/cargo_test.sh &

	wait
done

exit 0



