#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -eu

cr=$(dirname $0)
cd $cr
remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		# Handle delete
		:
	else
		if [ "$remote_sha" = $z40 ]
		then
			# New branch, examine all commits
			range="$local_sha"
		else
			# Update to existing branch, examine new commits
			range="$remote_sha..$local_sha"
		fi
	fi
	./hooks/pre-push/cargo_lint.sh &
	cargo_lint_proc=$!
	./hooks/pre-push/cargo_test.sh &
	cargo_test_proc=$!
	wait $cargo_lint_proc
	wait $cargo_test_proc

	wait
done

exit 0



